### PR TITLE
thunar-as-root-removed

### PR DESCRIPTION
**Pull request by VinayChaurasiyaA**

### CODE REVIEW

**Review by Rishabh672003 — CHANGES_REQUESTED** [review]
we dont need to do this, that is dont have to reemove both files
just remove the following lines 
https://github.com/tcet-opensource/tcet-linux-settings/blob/b3d697ee0aab0032b6dfb002bd09849c4ec81d30/etc/skel/.config/Thunar/uca.xml#L13-L26

**Review by VinayChaurasiyaA — COMMENTED** [review]
G2g

**Review by Rishabh672003 — APPROVED** [review]
LGTM

**Review by Akash6222 — APPROVED** [review]
GTG

**Pull request merged**
